#!/usr/bin/env bash

# Include 'os-release' to grab OS pretty name...

. /etc/os-release                                                              

# Styles...

red="$(tput setaf 1)"
bold="$(tput bold)"
reset="$(tput sgr0)"

# Vars
email="jesherdevsk8@gmail.com"
github="github.com/jesherdevsk8"

# Get terminal col width...

cols=$(tput cols)

# Main...

clear

echo "
$red        ____________  __  ____________  $reset ${bold}Email:${reset} $email
$red       / / ____/ ___// / / / ____/ __ \ $reset ${bold}$PRETTY_NAME${reset}
$red  __  / / __/  \__ \/ /_/ / __/ / /_/ / $reset ${bold}Kernel:${reset} $(uname -rm)
$red / /_/ / /___ ___/ / __  / /___/ _, _/  $reset ${bold}Uptime:${reset} $(uptime -p | cut -d' ' -f2-)
$red \____/_____//____/_/ /_/_____/_/ |_|   $reset ${bold}$USER@$HOSTNAME${reset} | ${bold}Github:${reset} $github
"

printf -- "-%.s" $(seq $cols)
echo -e "\n"

exit 0
